In [1]:
import numpy as np
import pandas as pd

##### Question No 1

In [2]:
pd.__version__

'3.0.6'

In [3]:
url ='https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'

In [4]:
df = pd.read_csv(url)
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

##### Question No 2

In [5]:
df.shape

(10000, 11)

##### Question No 3

In [6]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

##### Question No 4

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

##### Question No 5

In [8]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

##### Question No 6

In [9]:
df['horsepower'].median()

np.float64(254.0)

In [10]:
hrspwr_frequent_val = df['horsepower'].mode()
hrspwr_frequent_val

0    252.0
Name: horsepower, dtype: float64

In [11]:
hrspwr_frequent_val_filled = df['horsepower'].fillna(hrspwr_frequent_val[0])
hrspwr_frequent_val_filled.median()

np.float64(252.0)

In [12]:
hrspwr_frequent_val_filled.isnull().sum()

np.int64(0)

##### Question No 7

In [13]:
df_asia = df[df['origin'] == 'Asia']
df_subset = df_asia[['vehicle_weight', 'model_year']].head(7)
df_subset

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [14]:
X = df_subset.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [15]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [16]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [17]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [18]:
w = XTX_inv @ X.T @ y
w.sum()

np.float64(0.36919696904925486)