In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [2]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv"
df = pd.read_csv(url)
print(len(df), len(df.columns))
df.head()

5000 9

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [4]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [5]:
df['industry'].unique()

<StringArray>
[   'technology',        'retail', 'manufacturing',     'education',
    'healthcare',             nan,       'finance']
Length: 7, dtype: str

In [7]:
df['industry'].mode()[0]

'technology'

In [11]:
df['industry'].value_counts()

industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
Name: count, dtype: int64

In [13]:
df.columns

Index(['lead_source', 'industry', 'employment_status', 'location',
       'annual_income', 'number_of_courses_viewed', 'interaction_count',
       'lead_score', 'converted'],
      dtype='str')

In [14]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

### Data preparation

In [22]:
str_cols = df.select_dtypes(include=['str']).columns
numerical_cols =df.select_dtypes(include=['number']).columns

In [25]:
df[str_cols] = df[str_cols].fillna('NA')
df[numerical_cols] = df[numerical_cols].fillna(0.0)

In [31]:
df.isnull().sum()

lead_source                 0
industry                    0
employment_status           0
location                    0
annual_income               0
number_of_courses_viewed    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

### Question 1

In [32]:
df['industry'].value_counts()

industry
technology       1173
retail            925
healthcare        840
finance           720
education         639
manufacturing     463
NA                240
Name: count, dtype: int64

### Question 2

In [35]:
correlation_cols = ['interaction_count', 'lead_score', 'number_of_courses_viewed', 'annual_income']
corr_matrix = df[correlation_cols].corr()
corr_matrix

,interaction_count,lead_score,number_of_courses_viewed,annual_income
interaction_count,1.000000,0.915746,0.721609,0.122842
lead_score,0.915746,1.000000,0.757204,0.229496
number_of_courses_viewed,0.721609,0.757204,1.000000,0.161300
annual_income,0.122842,0.229496,0.161300,1.000000

In [36]:
print(f"1. interaction_count & lead_score: {corr_matrix.loc['interaction_count', 'lead_score']:.4f}")
print(f"2. number_of_courses_viewed & lead_score: {corr_matrix.loc['number_of_courses_viewed', 'lead_score']:.4f}")
print(f"3. number_of_courses_viewed & interaction_count: {corr_matrix.loc['number_of_courses_viewed', 'interaction_count']:.4f}")
print(f"4. annual_income & interaction_count: {corr_matrix.loc['annual_income', 'interaction_count']:.4f}")

1. interaction_count & lead_score: 0.9157
2. number_of_courses_viewed & lead_score: 0.7572
3. number_of_courses_viewed & interaction_count: 0.7216
4. annual_income & interaction_count: 0.1228

#### Split the data

### Question 3

### Question 4

### Question 5

### Question 6